{{- $COMPONENT_NAME := "backend" -}}
{{- $ROUTES := .Values.route.routesMapping -}}
{{- $CONTEXT := . -}}
{{- range $ROUTES -}}
{{ include "mc-chart.route" (dict "COMPONENT_NAME" $COMPONENT_NAME "ROUTE" . "context" $CONTEXT) }}
---
{{- end -}}
