import { EntityDescriptorModelType } from '../../../models';
import { uidescriptorFielsdName } from '../../../../common/ui-descriptors/helper';

export const getUIIngestionFieldDescriptors = (entityDescriptors: EntityDescriptorModelType[]) => {

  return uidescriptorFielsdName.map((desc) => {
      return {
        ...desc,
        isRequired: true,
        isAutoGenerated: false,
        infoMsgCode: ['info-general-tooltip.required'],
      }
    });
};