import { resolutionDegree } from '../../../../common/ui-descriptors/resolution/resolutionDegree';
import { resolutionMeter } from '../../../../common/ui-descriptors/resolution/resolutionMeter';
import { EntityDescriptorModelType } from '../../../models';

export const getUIIngestionFieldDescriptors = (entityDescriptors: EntityDescriptorModelType[]) => {
  const ingestionUiDescriptorFieldNames = [resolutionDegree, resolutionMeter];

  return ingestionUiDescriptorFieldNames.map((desc) => {
      return {
        ...desc,
        isRequired: true,
        isAutoGenerated: false,
        infoMsgCode: ['info-general-tooltip.required'],
      }
    });
};