import { Mode } from '../../../../common/models/mode.enum';
import { resolutionDegree } from '../../../../common/ui-descriptors/resolution/resolutionDegree';
import { resolutionMeter } from '../../../../common/ui-descriptors/resolution/resolutionMeter';
import { Status } from '../../../models';
import { IContext } from './state-machine/types';

export const getUIIngestionFieldDescriptors = () => {
  const ingestionUiDescriptorFieldNames = [resolutionDegree, resolutionMeter];

  return ingestionUiDescriptorFieldNames.map((desc) => {
    return {
      ...desc,
      isRequired: true,
      isAutoGenerated: false,
      infoMsgCode: ['info-general-tooltip.required'],
    };
  });
};

export const isLayerLocked = (context: IContext): boolean => {
  return (
    context.selectionMode === 'restore' &&
    context.flowType === Mode.UPDATE &&
    ![Status.Completed, Status.Aborted].includes(context.job?.details?.status as Status)
  );
};
