name: CI

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  helm-lint:
    name: Run Helm lint Check
    runs-on: ubuntu-latest
    steps:
      - name: helm-lint
        uses: MapColonies/shared-workflows/actions/helm-lint@helm-lint-v1

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.13.x]
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends yarn
      - name: Install dependecies
        run: yarn
      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          tsc: true
          eslint: true
          prettier: true
          eslint_extensions: ts
      - name: Test
        run: yarn test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
